### ISSUE TITLE
zombies should have a "hat" layer

### ISSUE THREAD

**Issue by kingoscargames** [maikerumine/mobs_mc#89] opened 2017-07-05 18:38 UTC
<img width="912" alt="zombie2" src="https://user-images.githubusercontent.com/29333817/27879409-cef44b44-61c1-11e7-98af-e24727877ee4.png">

**Comment by Wuzzy2** [comment] 2017-07-05 20:16
You should explain this.
Also: Patches are welcome.

Also: Please talk to @22i about model and mob texture issues. https://github.com/22i/amc/issues

**Comment by kingoscargames** [comment] 2017-07-05 20:44
The zombies in mc have a overlay for the "hat" just like players.
The same as the default player: ![character](https://user-images.githubusercontent.com/29333817/27884100-5b82d1a0-61d3-11e7-82be-dd69ac6023c6.png)

**Comment by 22i** [comment] 2017-07-16 19:30
will do this

**Comment by Wuzzy2** [comment] 2017-07-23 14:55
There is now a new zombie texture which appears to have the “hat” texture as requested.
But it doesn't look like this special layer is actually used in the mesh. So the issue is not actually fixed yet.
@22i: Did you fix the zombie mesh yet?

**Comment by 22i** [comment] 2017-07-23 20:31
not yet

**Comment by 22i** [comment] 2017-07-24 11:08
@kingoscargames  @Wuzzy2  done it - now the zombie and baby zombie both have a hat layer

https://github.com/22i/amc/blob/master/models/mobs_mc_zombie.b3d

https://github.com/22i/amc/blob/master/models/mobs_mc_zombie_baby.b3d

**Comment by Wuzzy2** [comment] 2017-11-03 14:16
Zombies have a “hat” layer since a while now. Closing.

**Closed as completed by Wuzzy2** 2017-11-03 14:16 UTC
Labels: bug
